server:
  port: 8081
spring:
  application.name: organization-service
  profiles:
    active: dev
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: https://localhost:8071
      fail-fast: true
  datasource:
    url: jdbc:postgresql://localhost:5432/organization_db
    username: admin
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        show_sql: true
        format_sql: true
eureka:
  client:
    service-url:
      defaultZone: https://localhost:8070/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      enabled: true
    env:
      enabled: true
      show-values: always